//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GÖKSUKESEN\\SQLEXPRESS;Initial Catalog=deneme3;Integrated Security=Tru" +
            "e;Encrypt=True;TrustServerCertificate=True")]
        public string deneme3ConnectionString {
            get {
                return ((string)(this["deneme3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GÖKSUKESEN\\SQLEXPRESS;Initial Catalog=17.12.24database;Integrated Sec" +
            "urity=True;Encrypt=True;TrustServerCertificate=True")]
        public string _17_12_24databaseConnectionString {
            get {
                return ((string)(this["_17_12_24databaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CAKMAK;Initial Catalog=28.12.24_RMS;Integrated Security=True;TrustSer" +
            "verCertificate=True")]
        public string _28_12_24_RMSConnectionString {
            get {
                return ((string)(this["_28_12_24_RMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GÖKSUKESEN\\SQLEXPRESS;Initial Catalog=RestaurantManagementProject;Int" +
            "egrated Security=True;TrustServerCertificate=True")]
        public string RestaurantManagementProjectConnectionString {
            get {
                return ((string)(this["RestaurantManagementProjectConnectionString"]));
            }
        }
    }
}
